### ISSUE TITLE
Починить картинки

### ISSUE THREAD

**Issue by v2do5** [wondersell/wondercard-front#1]
При переносе редактора в тильду, сломались картинки:
http://wondercard.tilda.ws/editor 

Нужно поправить редактор, как он был в самом начале: 
http://tech-law.ru/wondercard/

Обратить внимание на:

- Все иконки в верхнем меню на желтом фоне: плюсики, лого, слои, undo/redo и тд
- Иконки редактора: основные и внутренние, например, при нажатии на «Трансофрмация» или «Текст»
- Иконки в верхнем меню при выборе слоя
- Иконки в модальном меню при выборе слоя
- Позиционирование иконок и размер элементов управления, например, размер шрифта и т.д.

Также, необходимо поправить размер холста по умолчанию. Сейчас он почему-то увеличен в размере. Необходимо сделать его под размер экрана по высоте.

**Comment by v2do5** [comment]
Починил изображения для https://wondercard.netlify.app/ с помощью настройки baseUrl: baseUrl: 'https://wondercard.netlify.app/'

Но если встроить код редактора в тильду, то все равно картинки не работают. Можно прописать прямые ссылки для иконок редактора верхнего уровня, которые есть в настройках, но это очень частично решает проблему, так как у них все равно теряется позиционирование по центру и сбивается ширина блоков. При этом остальные изображения все равно не работают, например, иконки самого верхнего желтого блока.

Нужна помощь @hemantic

**Comment by hemantic** [comment]
Решили с Тильдой не мучаться, потому что это бесполезно.
