### ISSUE TITLE
Наполнить раздел «Фигуры»

### ISSUE THREAD

**Issue by v2do5** [wondersell/wondercard-front#16]
В разделе «Фигуры» создать и наполнить несколько папок:

- [x] Стрелки
- [x] Геометрия и декор
- [x] Кляксы
- [x] Значки
- [x] Текстовые значки
- [x] Иконки

Архивы с элементами будут постепенно добавляться
[Стрелки.zip](https://github.com/wondersell/wondercard-front/files/6719888/default.zip)
[Геометрия и декор.zip](https://github.com/wondersell/wondercard-front/files/6719913/default.zip)

**Comment by hemantic** [comment]
Стрелки и декор добавил, над самими ассетами (точнее, настройками экспорта в SVG) нужно сильно подумать.
