### ISSUE TITLE
Разобраться в настройках разделов редактора

### ISSUE THREAD

**Issue by v2do5** [wondersell/wondercard-front#3]
В редакторе есть разделы:

1. Фигуры
2. Объекты
3. Рамка

Нужно решить следующие задачи:
- [x] Понять, как кастомизировать наполнение своим содержимым. Результат: инструкция для замены объектов и их лейблов. 

- [x] Понять как убирать (добавлять) действия с объектами. 

В качестве пример решить задачу:
В фигурах должны быть векторные рисунки, например, в формате svg. 
В объектах должны быть растровые изображения.
Разница между ними в том, что в векторных изображениях можно настроить заливку цвета, например сделать стрелку красным цветом, вместо стандартного черного. А в объектах, поменять цвет изображения редактор не дает. Поэтому, при редактировании **фигуры** кнопка «Цвет» должна быть, а при редактировании **объекта** ее быть не должно.

- [x] Убрать шаг «Применить», при добавлении нового объекта/фигуры. Сейчас при выборе объекта/фигуры редактор размещает его на холсте и требует нажать кнопку «Применить», чтобы перейти к настройкам. Это действие лишнее: при выборе и добавлении объекта сразу должно появляться редактирование объекта

- [x]  Понять, как менять иконки при редактировании объекта, например: цвет, тень, контур, фон и т.д. Результат: инструкция для замены иконок. 

- [x] Понять, как менять библиотеку тектстур и градиентов при редактировании объекта.
Результат: инструкция для замены текстур/градиентов и их лейблов.

**Comment by hemantic** [comment]
**Как менять фигуры и их лейблы**

Для изменения набора фигур существует настройка редактора `tools.stickers`. В ней параметр нужно указать параметр `replaceDefault: true` и в поле `items` перечислить набор фигур в том же формате, как они перечислены в стандартной поставке (см. ниже). 

Структура раздела "Объекты" по-умолчанию настраивается в файле `src/app/image-editor/tools/shapes/default-stickers.ts`. В нем нужно указать название раздела, количество элементов в разделе и ссылку на файл с ассетсами. Каждый файл ассетов – это SVG файл, лежащий в папке `src/assets/images/ui/`, содержащий набор элементов (например, `src/assets/images/ui/beach.svg` содержит пляжи). В нем должно быть столько объектов, сколько было указано в конфиге.

**Как менять объекты и их лейблы**

Для изменения набора фигур существует настройка редактора `tools.shapes`. В ней параметр нужно указать параметр `replaceDefault: true` и в поле `items` перечислить набор фигур в том же формате, как они перечислены в стандартной поставке (см. ниже). 

Конфигурация раздела "Объекты" находится в файле `src/app/image-editor/tools/shapes/default-shapes.ts`. В списке `defaultShapes` нужно задать набор объектов, которые будут отрисованы. Для каждого объекта нужно задать подпись (поле `name`), тип объекта (поле `type`) и SVG представление объекта (поле `options.path`) 

Редактор знает 5 базовых типов объектов (именно с большой буквы):

* `Circle` – круг, настроек нет
* `Rect`  – квадрат, настроек нет
* `Triangle` – треугольник, настроек нет
* `Ellipse` – круг, какие-то настройки есть, но можно считать что нет
* `Path` – фигура, единственный тип, который можно загружать

Я подозреваю, что все новые фигуры будут с типом `Path`

**Comment by hemantic** [comment]
**Как менять градиенты**

Для градиентов настроек нет, так что придется их менять в исходниках и пересобирать библиотеку. Набор градиентов задается в файле `src/app/image-editor/tools/gradient-presets.ts`, с настройками нужно экспериментировать.

**Comment by hemantic** [comment]
**Как менять иконки при редактировании объекта**

Набор действий, подписи и иконки к ним меняются в этом разделе конфигурации:

```
nav: {
    position: NavPosition.TOP,
    replaceDefault: false,
    items: [
        {name: 'filter', icon: 'filter-custom', action: DrawerName.FILTER},
        {type: 'separator'},
        {name: 'resize', icon: 'resize-custom', action: DrawerName.RESIZE},
        {name: 'crop', icon: 'crop-custom', action: DrawerName.CROP},
        {name: 'transform', icon: 'transform-custom', action: DrawerName.TRANSFORM},
        {type: 'separator'},
        {name: 'draw', icon: 'pencil-custom', action: DrawerName.DRAW},
        {name: 'text', icon: 'text-box-custom', action: DrawerName.TEXT},
        {name: 'shapes', icon: 'polygon-custom', action: DrawerName.SHAPES},
        {name: 'stickers', icon: 'sticker-custom', action: DrawerName.STICKERS},
        {name: 'frame', icon: 'frame-custom', action: DrawerName.FRAME},
        {type: 'separator'},
        {name: 'corners', icon: 'rounded-corner-custom', action: DrawerName.CORNERS},
        {name: 'background', icon: 'background-custom', action: DrawerName.BACKGROUND},
        {name: 'merge', icon: 'merge-custom', action: DrawerName.MERGE},
    ]
},
```

**Comment by hemantic** [comment]
Ну, здесь всё. Теперь нужны сами фигуры, градиенты и прочее. Думаю, я смогу собирать их в наборы и прикручивать разные в зависимости от шаблона.

**Comment by v2do5** [comment]
> **Как менять иконки при редактировании объекта**
> 
> Набор действий, подписи и иконки к ним меняются в этом разделе конфигурации:
> 
> ```
> nav: {
>     position: NavPosition.TOP,
>     replaceDefault: false,
>     items: [
>         {name: 'filter', icon: 'filter-custom', action: DrawerName.FILTER},
>         {type: 'separator'},
>         {name: 'resize', icon: 'resize-custom', action: DrawerName.RESIZE},
>         {name: 'crop', icon: 'crop-custom', action: DrawerName.CROP},
>         {name: 'transform', icon: 'transform-custom', action: DrawerName.TRANSFORM},
>         {type: 'separator'},
>         {name: 'draw', icon: 'pencil-custom', action: DrawerName.DRAW},
>         {name: 'text', icon: 'text-box-custom', action: DrawerName.TEXT},
>         {name: 'shapes', icon: 'polygon-custom', action: DrawerName.SHAPES},
>         {name: 'stickers', icon: 'sticker-custom', action: DrawerName.STICKERS},
>         {name: 'frame', icon: 'frame-custom', action: DrawerName.FRAME},
>         {type: 'separator'},
>         {name: 'corners', icon: 'rounded-corner-custom', action: DrawerName.CORNERS},
>         {name: 'background', icon: 'background-custom', action: DrawerName.BACKGROUND},
>         {name: 'merge', icon: 'merge-custom', action: DrawerName.MERGE},
>     ]
> },
> ```

Насколько я понимаю, эти настройки меняют вот это меню:
![image](https://user-images.githubusercontent.com/2041963/123477995-86d2a900-d607-11eb-8736-590347d1dc17.png)
Оно уже настроено

Нужно еще настроить внутреннее меню, которое отображается при выделении слоя:
![image](https://user-images.githubusercontent.com/2041963/123478108-a8cc2b80-d607-11eb-9a31-579e585cdd40.png)
Как я понял оно не здесь редактируется или я не прав?

**Comment by v2do5** [comment]
> Ну, здесь всё. Теперь нужны сами фигуры, градиенты и прочее. Думаю, я смогу собирать их в наборы и прикручивать разные в зависимости от шаблона.

Оке. 
Думаю, что наборы должны быть универсальными. На мой вкус нужна коллекция стандартных элементов, которые подходят под все шаблоны или даже если пользователь собирает карточку с нуля.

**Comment by v2do5** [comment]
> > Понять как убирать (добавлять) действия с объектами.
> 
> С помощью настроек редактор не поддерживает изменение набора действий с объектами, а логика отрисовки меню не предполагает каких-то изменений. Поэтому предлагаю оставить этот пункт на попозже, когда решим что пришла пора глубоко перерабатывать редактор.

А, если ты про под меню, то я понял. Там хотяб иконки безболезненно можно поменять или не очень?

**Comment by hemantic** [comment]
> Там хотяб иконки безболезненно можно поменять или не очень?

Просто взять и подменить файлы на свои нам никто не запретит.
