### ISSUE TITLE
Убрать обводку

### ISSUE THREAD

**Issue by v2do5** [wondersell/wondercard-front#34]
При изменении цвета у объектов появляется очень странная обводка непонятной природы происхождения:
![image](https://user-images.githubusercontent.com/2041963/124466431-56290700-dd9f-11eb-92ad-dbca404987c7.png)

Особенно заметна на светлых цветах
В свг файлах никаких настроек обводки нет, при этом несколько раз по разному экспортировал объекты, в том числе с полностью прозрачной обводкой — все равно та же херь. Будто это редактор сам что-то накладывает.

**Comment by hemantic** [comment]
Вроде готово, можно проверять. Обошлось без модификации исходников.
