### ISSUE TITLE
Снять лок для аспект ратио

### ISSUE THREAD

**Issue by v2do5** [wondersell/wondercard-front#36]
Есть стандартный набор фигур в разделе «Фигуры» с иконкой сердечком
Нужно снять лок на аспект ратио у объектов внутри.
То есть штобы круг можно было сделать овалом, квадрат прямоугольником и тд

Объекты из раздела стикеров пострадать не должны. Они должны работать с локом.

**Comment by hemantic** [comment]
Я не уверен, что это какой-то лок, который можно как-то снять. Судя по всему, эта функция в принципе в редакторе не реализована и я пока не очень знаю как и где её вообще делать.

**Comment by hemantic** [comment]
Хотя нет, нашел. Теперь у объектов, вставленных из раздела "Фигуры" можно менять аспект ратио, у текстов и объектов из раздела "Объекты" – нельзя.
