### ISSUE TITLE
Встроить json шаблон в код редактора

### ISSUE THREAD

**Issue by v2do5** [wondersell/wondercard-front#4]
При выборе шаблона в каталоге, сайт будет направлять пользователя на страницу с уникальным кодом редактора, в который будет встроен выбранный json шаблон. 

Нужно создать отдельную страницу с примером того, как будет выглядеть код с втроенным в него вот этим шаблоном: 
[1-1.json.zip](https://github.com/wondersell/wondercard-front/files/6664294/1-1.json.zip) (json находится внутри зипа)

Сейчас шаблоны загружаются в редактор через синюю кнопку «Добавить» слева сверху и пунктом меню «Добавить исходник»

**Comment by hemantic** [comment]
Шаблоны можно загружать через опцию `image: '/presets/1-1.json',`, добавил для примера.
