### ISSUE TITLE
Разработать каталог шаблонов 

### ISSUE THREAD

**Issue by v2do5** [wondersell/wondercard-front#5]
Необходимо сделать на Тильде страницу с перечнем шаблонов. Сверху надо разместить фильтр по тематике, типу шаблона, совместимости и т.д. 

На месте первого шаблона должна быть кнопка для открытия пустого редактора.

На готовых шаблонах должны быть предусмотрены лейблы: 

- Бесплатный
- Доступен в платной версии

Каждый шаблон должен вести на отдельную страницу с кодом редактора со встроенным в него json шаблоном.

Должно быть предусмотрено 2 версии страницы:

- [x] Фримиум пользователи без возможности перейти в редактор платного шаблона
- [x] Оплаченные пользователи с возможностью перейти в редактор платного шаблона

В качестве референса можно посмотреть на:
![image](https://user-images.githubusercontent.com/2041963/122283931-bf7ece00-cef5-11eb-968f-e308556b1afb.png)
и
![image](https://user-images.githubusercontent.com/2041963/122285711-bd1d7380-cef7-11eb-9f66-c9190d5d2ff9.png)

**Comment by v2do5** [comment]
Создан перечень разных категорий шаблонов: 
Красота и здоровье
Мода и стиль
Еда и напитки
Товары для дома и сада
Товары для кухни
Спорт
Искусство и рукоделие
Домашние животные
Электроника
Авто
Дети
Медицина
Книги
Путешествия
Офис
Инструменты

Они будут фильтроваться через галочки и инструмент «Фильтры»

В то же время, созданы 2 категории «Фримуим» и «Оплаченный пользователь» через инструмент «Категории». 

На странице бесплатных пользователей будет отображаться только категория «Фримуим»
На странице оплаченных пользователей будет отображаться только категория «Оплаченный пользователь»

Меню фильтрации по категориям не будет отображаться пользователям и служит исключительно для сортировки платных и бесплатных шаблонов.

**Comment by v2do5** [comment]
Сделаны 2 страницы для бесплатных и платных пользователей:
http://wondercard.tilda.ws/templates-freemium
http://wondercard.tilda.ws/templates-paid-user

На этих страницах находятся разные товары. У бесплатных пользователей товары отображаются с пометкой об оплате. 

У всех пользователей первым товаром установлена карточка с созданием шаблона с нуля. Сейчас на ней уставлен яркий элемент привлекающий внимания. 

Вопрос к @hemantic: нужно ли его оставлять так, или сделать его более нейтральным, чтобы сфокусировать внимание пользователей на готовых шаблонах?

**Comment by hemantic** [comment]
Надо будет посмотреть на реальных шаблонах, но я бы пока оставил так. Мне нравится.
