### ISSUE TITLE
Бесплатная версия редактора

### ISSUE THREAD

**Issue by v2do5** [wondersell/wondercard-front#6]
Необходимо разработать версию редактора для бесплатной группы пользователей.
Некоторые кнопки в основном меню редактора должны быть заглушены и на них должен быть нанесен лейбл со значком рубля, при нажатии на который будет открываться страница с выбором тарифа. 

- [ ] Вадим должен разработать дизайн заглушки и лейбла
- [ ] Артему нужно поправить редактор с предложенным вариантом дизайна

Результат: Страница на тильде с бесплатной версией редактора и пустым шаблоном.

**Comment by hemantic** [comment]
Решили, что бесплатная версия – это простенький шаблон.

**Comment by hemantic** [comment]
Закрыто в пользу #25
